version: "3.9"

services:
  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: [ "-config.file=/etc/loki/loki-config.yml" ]
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
      - ./loki:/loki
    networks:
      - observability

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    command: [ "-config.file=/etc/promtail/promtail-config.yml" ]
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - ./logs:/var/log/app:ro
    networks:
      - observability
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # Configuration SMTP (Gmail)
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=technotechsn@gmail.com
      - GF_SMTP_PASSWORD=yxizcpeaznjcmuho  
      - GF_SMTP_FROM_ADDRESS=technotechsn@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Alerts
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    networks:
      - observability
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - observability

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - observability


networks:
  observability:

volumes:
  grafana_data:
  prometheus_data:
