version: "3.9"

services:
  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: [ "-config.file=/etc/loki/loki-config.yml" ]
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
      - ./loki:/loki
    networks:
      - observability

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    command: [ "-config.file=/etc/promtail/promtail-config.yml" ]
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - ./logs:/var/log/app:ro
    networks:
      - observability
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    networks:
      - observability
    depends_on:
      - loki

networks:
  observability:

volumes:
  grafana_data:
